### ISSUE TITLE
Migrations for Django 2.2 fail

### ISSUE THREAD

**Issue by dominicrodger** [tmm/django-username-email#16]
Hi,

I just tried upgrading my development environment (using django-username-email 2.2.2) to Django 2.2, and when I ran `migrate`, I got this:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/contrib/auth/migrations/0011_update_proxy_permissions.py", line 35, in update_proxy_model_permissions
    ).update(content_type=new_content_type)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/models/query.py", line 741, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1426, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    cursor.execute(sql, params)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dom/.virtualenvs/churchsimple/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_permission_content_type_id_codename_01ab375a_uniq"
DETAIL:  Key (content_type_id, codename)=(6, add_group) already exists.
```

In this case, the old content type being moved from was `auth`, and the new one was `cuser`. Looking in my database, I appear to have the following:

```
>>> from django.contrib.auth.models import Permission
>>> foo = list(Permission.objects.all())
>>> foo = [obj for obj in foo if obj.codename == 'add_group']
>>> foo
[<Permission: auth | group | Can add group>, <Permission: cuser | group | Can add group>]
```

Any ideas of how to fix this? I think I could probably fix by removing all the `Permission` objects with content type `cuser` right before the upgrade, but curious if you have better ideas, of if there's a way to fix this in django-username-email itself.

**Comment by ataylor32** [comment]
I upgraded a Django 2.1 project to Django 2.2 and didn't run into this. Out of curiosity, which version of Django did you upgrade from?

**Comment by dominicrodger** [comment]
Interesting - I was upgrading from Django 2.1.7 - perhaps I messed something up locally (I added django-username-email part-way through the project IIRC).

**Comment by dominicrodger** [comment]
I'll close this - this appears to have been a one off, I just resynced my dev database from production and migrations were fine, and then migrated in production and that went fine too.
