### ISSUE TITLE
`AttributeError: type object 'SetPasswordMixin' has no attribute 'create_usable_password_field'.`

### ISSUE THREAD

**Issue by muety** [tmm/django-username-email#28]
There seems to be a bug when using this library with Django 5.1.1. Probably related to one of the recent changes to `django.contrib.auth.forms`, see [here](https://github.com/django/django/commits/main/django/contrib/auth/forms.py).

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/sentry_sdk/integrations/threading.py", line 72, in run
    reraise(*_capture_exception())
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/sentry_sdk/_compat.py", line 127, in reraise
    raise value
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/sentry_sdk/integrations/threading.py", line 70, in run
    return old_run_func(self, *a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 126, in inner_run
    autoreload.raise_last_exception()
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/contrib/admin/__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/myuser/myproject/portal/admin.py", line 1, in <module>
    from cuser.admin import UserAdmin as CUserAdmin
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/cuser/admin.py", line 8, in <module>
    from cuser.forms import UserChangeForm, UserCreationForm
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/cuser/forms.py", line 95, in <module>
    class UserCreationForm(SetPasswordMixin, forms.ModelForm):
  File "/home/myuser/myproject/venv/lib/python3.12/site-packages/cuser/forms.py", line 107, in UserCreationForm
    usable_password = SetPasswordMixin.create_usable_password_field()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'SetPasswordMixin' has no attribute 'create_usable_password_field'. Did you mean: 'create_password_fields'?
```

**Comment by ataylor32** [comment]
Thanks for reporting this! This was fixed in b06b938b8137f1a0c33afbdf63151efc548c354b / version 2.5.6
